package com.github.rickart.softserve.task.algorithm;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class SimpleAlgorithmStrategyFactoryTest {

    @Test
    public void shortStringTest() {
        SimpleAlgorithmStrategyFactory factory = new SimpleAlgorithmStrategyFactory();
        AlgorithmStrategy strategy = factory.createStrategy("a");
        assertEquals(StreamAlgorithmStrategy.class, strategy.getClass());
    }

    @Test
    public void longStringTest() {
        String longString = "qJwZOXyPjWULEiYbV6kxzoh0PXsZYfntAidh1aiM6CoTCDAMroBehOx8AvOylFCVtYzWkRWtlxJnHJukdkT3eZiNLL97TVTSZbtsFAW5gTu8cGINeGVW06zKpq97AsoA0nMPyBTcdnjM8ra130nZqd8g077YYb02lfBppaBE7mpC1YPmOKocDGmoz2mmCyggzBykHYMP6WwqRbFOoTTYqkatoq7e9XSx2P7F4uEAqM3KeEu0oboLvmy2v3hYZWa8et8hJYCsI63w0WZlSF3Y34iUAchW6KqOQV7uCOWgjbpzTshwDvzl4unb3ZkarBM8DLfnYtD2dsN5wMjA4b0AkBaD9wbOXnt447ztGQzYGW3BOX6wJkopUM90hztvntURMA8by1UZwMnKrhyPLkwvGDhVxMHPWyRAf6BYxCXEjCyosE9fbXJ5MrfvwUb5Fxt4dAgYwDE6jM5QV4bOprpBCjpjfb0CJ8H7OPURkBTcOg1wgTxfEizYKpcL98KH8TqY6o1ATDY3ztVsK2hbvFAv3ZaqC7poYuHwevoZn1BeOizIpl6RpotGMrrZFFVDEDq9e2Ri1bJFjKrElaPWg0YD93NthYrtipw9XoXPMKhlzIJVyw9EbEXk4CY0F0YjtfuGIqgrQudzIlTY1LJ62mlgwp0cwDBVHsqzKhA9zBGv68LiTvWXYylXua7aBCpuc9bVWUMMNYo5QJDWYlX1bQKPcu2FLmQXWcLXw0xHoK6vRpuIFFocxYWLLaWmh2FxklE9Rgupoyy6IktF3wrrpmACq4ZHQqPyfpWqJwZOXyPjWULEiYbV6kxzoh0PXsZYfntAidh1aiM6CoTCDAMroBehOx8AvOylFCVtYzWkRWtlxJnHJukdkT3eZiNLL97TVTSZbtsFAW5gTu8cGINeGVW06zKpq97AsoA0nMPyBTcdnjM8ra130nZqd8g077YYb02lfBppaBE7mpC1YPmOKocDGmoz2mmCyggzBykHYMP6WwqRbFOoTTYqkatoq7e9XSx2P7F4uEAqM3KeEu0oboLvmy2v3hYZWa8et8hJYCsI63w0WZlSF3Y34iUAchW6KqOQV7uCOWgjbpzTshwDvzl4unb3ZkarBM8DLfnYtD2dsN5wMjA4b0AkBaD9wbOXnt447ztGQzYGW3BOX6wJkopUM90hztvntURMA8by1UZwMnKrhyPLkwvGDhVxMHPWyRAf6BYxCXEjCyosE9fbXJ5MrfvwUb5Fxt4dAgYwDE6jM5QV4bOprpBCjpjfb0CJ8H7OPURkBTcOg1wgTxfEizYKpcL98KH8TqY6o1ATDY3ztVsK2hbvFAv3ZaqC7poYuHwevoZn1BeOizIpl6RpotGMrrZFFVDEDq9e2Ri1bJFjKrElaPWg0YD93NthYrtipw9XoXPMKhlzIJVyw9EbEXk4CY0F0YjtfuGIqgrQudzIlTY1LJ62mlgwp0cwDBVHsqzKhA9zBGv68LiTvWXYylXua7aBCpuc9bVWUMMNYo5QJDWYlX1bQKPcu2FLmQXWcLXw0xHoK6vRpuIFFocxYWLLaWmh2FxklE9Rgupoyy6IktF3wrrpmACq4ZHQqPyfpW";
        SimpleAlgorithmStrategyFactory factory = new SimpleAlgorithmStrategyFactory();
        AlgorithmStrategy strategy = factory.createStrategy(longString);
        assertEquals(LinearAlgorithmStrategy.class, strategy.getClass());
    }
}